[package]
name = "yaml_alignment_validator"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
tera = "1.17"
tokio = { version = "1.0", features = ["full"] }
toml = "0.5"